const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const fs = require('node:fs');
(async()=>{
const logoData = fs.readFileSync(__dirname + '/src/resources/certificatesConfig/assets/logo-assinae.png');
const pdf = await PDFDocument.create();
const page = pdf.addPage([841.89,595.28]);
const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
const font = await pdf.embedFont(StandardFonts.Helvetica);
const width = page.getSize().width, centerX=width/2;
const logo = await pdf.embedPng(logoData);
const logoDims = logo.scaleToFit(96,38);
const qrSize=68,gap=16;
const linhaPor='Assinado digitalmente por',linhaNome='Maria Clara de Souza Oliveira',linhaData='em 13/07/2026 18:32',linhaCodigo='Codigo de verificacao: A1B2-C3D4-E5F6';
const sPor=7.5,sNome=12,sData=8.5,sCod=7.5;
const colWidth=Math.max(logoDims.width,font.widthOfTextAtSize(linhaPor,sPor),fontBold.widthOfTextAtSize(linhaNome,sNome),font.widthOfTextAtSize(linhaData,sData),font.widthOfTextAtSize(linhaCodigo,sCod));
const larguraQr=qrSize+gap, grupoWidth=larguraQr+colWidth, startX=centerX-grupoWidth/2, colX=startX+larguraQr;
const centerY=150, colHeight=logoDims.height+6+sPor+4+sNome+5+sData+4+sCod;
let cursorY=centerY+colHeight/2;
const NAVY=rgb(0.06,0.11,0.21),GRAY=rgb(0.4,0.45,0.52),LIGHT=rgb(0.58,0.64,0.72);
page.drawImage(logo,{x:colX,y:cursorY-logoDims.height,width:logoDims.width,height:logoDims.height});
cursorY-=logoDims.height+6;
page.drawText(linhaPor,{x:colX,y:cursorY-sPor,size:sPor,font,color:GRAY});cursorY-=sPor+4;
page.drawText(linhaNome,{x:colX,y:cursorY-sNome,size:sNome,font:fontBold,color:NAVY});cursorY-=sNome+5;
page.drawText(linhaData,{x:colX,y:cursorY-sData,size:sData,font,color:GRAY});cursorY-=sData+4;
page.drawText(linhaCodigo,{x:colX,y:cursorY-sCod,size:sCod,font,color:LIGHT});
page.drawRectangle({x:startX,y:centerY-qrSize/2,width:qrSize,height:qrSize,borderColor:NAVY,borderWidth:1});
const bytes = await pdf.save();
fs.writeFileSync('/sessions/charming-eager-sagan/mnt/outputs/stamp-sample.pdf', bytes);
console.log('OK bytes='+bytes.length+' logo='+logoDims.width.toFixed(1)+'x'+logoDims.height.toFixed(1)+' colWidth='+colWidth.toFixed(1)+' grupoWidth='+grupoWidth.toFixed(1)+' startX='+startX.toFixed(1)+' colX='+colX.toFixed(1));
})().catch(e=>{console.error('ERR',e.message);process.exit(1)});
